name: CircleCore
version: '${project.version}'
main: me.itsglobally.circlecore.CircleCore
load: STARTUP
commands:
  gamemode:
    aliases:
      - gm
      - gmc
      - gms
      - gma
      - gmsp
    permission: circlecore.gm
  help:
    description: "?"
  vanish:
    permission: circlecore.vanish
  nick:
    permission: circlecore.nick
permissions:
  circlecore.gm:
    default: op
  circlecore.vanish:
    default: op
  circlecore.nick:
    default: op