name: CircleCore
version: '${project.version}'
main: me.itsglobally.circlecore.CircleCore
load: STARTUP
commands:
  gamemode:
    aliases:
      - gm
      - gmc
      - gms
      - gma
      - gmsp
    permission: circlecore.gm
  help:
    description: "?"
permissions:
  circlecore.gm:
    default: op